version: "4"
services:
    # php service
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV={$APP_ENV}
        environment:
            - APP_ENV={$APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8001:8000
        depends_on:
            - database
            - node
        # networks:
        #     - app-network

    # Database server
    database:
        image: mysql:latest
        ports:
            - 3307:3306
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
        volumes:
            - db-data:/var/lib/mysql
        # networks:
        #     - app-network

    # phpmyadmin
    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=database
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
        depends_on:
            - database
        # networks:
        #     - app-network

    # Redis server
    # redis:
    #     image: redis:alpine
    #     command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    #     ports:
    #         - 6379:6379

    # node
    node:
        build:
            context: .
            target: node
        volumes:
            - .:/usr/src
            - ./node_modules:/usr/src/node_modules
        tty: true
        # networks:
        #     - app-network

volumes:
    db-data:
# #Docker Networks
# networks:
#     app-network:
#         driver: bridge
